package club.someoneice.humangunner;

import com.craftix.hostile_humans.entity.data.HumanData;
import com.craftix.hostile_humans.entity.entities.Human;
import com.craftix.hostile_humans.entity.entities.HumanTier;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.enchantment.EnchantmentHelper;
import net.minecraft.world.item.enchantment.Enchantments;

import java.util.Map;

/** Adds a one-time, tier-scaled enchantment roll to shields generated by Hostile Humans. */
public final class ShieldEnchantmentRoll {
    private static final String STACK_ROLLED = HumanGunner.MOD_ID + ":durability_enchantment_rolled";

    private ShieldEnchantmentRoll() {
    }

    public static void applyOnce(Human human) {
        for (EquipmentSlot slot : EquipmentSlot.values()) {
            applyToShield(human, human.getItemBySlot(slot));
        }

        HumanData data = human.getData();
        if (data != null) {
            for (int i = 0; i < data.getInventoryItemsSize(); i++) {
                applyToShield(human, data.getInventoryItem(i));
            }
        }
    }

    /** Applies exactly one tier-scaled durability roll to this physical stack. */
    public static void applyToShield(Human human, ItemStack shield) {
        if (!SpartanEquipmentCompat.isShield(shield)
                || (shield.hasTag() && shield.getTag().getBoolean(STACK_ROLLED))) {
            return;
        }
        shield.getOrCreateTag().putBoolean(STACK_ROLLED, true);
        RollProfile profile = profileFor(human);
        if (profile != null) {
            rollEnchant(human, shield, profile);
        }
    }

    private static void rollEnchant(Human human, ItemStack shield, RollProfile profile) {
        if (human.getRandom().nextFloat() >= profile.chance()) {
            return;
        }
        int level = human.getRandom().nextInt(profile.minimumLevel(), profile.maximumLevel() + 1);
        ItemStack enchanted = EnchantmentHelper.enchantItem(human.getRandom(), shield, level, false);
        Map<net.minecraft.world.item.enchantment.Enchantment, Integer> enchantments =
                EnchantmentHelper.getEnchantments(enchanted);
        int unbreaking = human.getRandom().nextInt(profile.minimumUnbreaking(), profile.maximumUnbreaking() + 1);
        enchantments.put(Enchantments.UNBREAKING,
                Math.max(unbreaking, enchantments.getOrDefault(Enchantments.UNBREAKING, 0)));
        if (human.getRandom().nextFloat() < profile.mendingChance()) {
            enchantments.put(Enchantments.MENDING,
                    Math.max(1, enchantments.getOrDefault(Enchantments.MENDING, 0)));
        }
        EnchantmentHelper.setEnchantments(enchantments, enchanted);
    }

    private static RollProfile profileFor(Human human) {
        if (TierThreeHuman.isTierThree(human)) {
            return new RollProfile(1.0F, 28, 38, 3, 3, 0.55F);
        }
        return switch (human.getTier()) {
            case LEVEL1 -> new RollProfile(0.72F, 12, 22, 2, 3, 0.12F);
            case LEVEL2 -> new RollProfile(0.88F, 20, 30, 3, 3, 0.25F);
            case ROAMER -> new RollProfile(0.70F, 12, 22, 2, 3, 0.10F);
            default -> null;
        };
    }

    private record RollProfile(
            float chance,
            int minimumLevel,
            int maximumLevel,
            int minimumUnbreaking,
            int maximumUnbreaking,
            float mendingChance
    ) {
    }
}
